version: '3.8'

services:
  feishu-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feishu-bot
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./code/config.yaml:/app/config.yaml
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  default:
    driver: bridge
