# Feishu配置
APP_ID: "cli_xxx"  # 飞书应用的App ID
APP_SECRET: "xxx"  # 飞书应用的App Secret
APP_VERIFICATION_TOKEN: "xxx"  # 飞书应用的Verification Token
APP_ENCRYPT_KEY: "xxx"  # 飞书应用的Encrypt Key
BOT_NAME: "ChatBot"  # 机器人名称

# AI提供商配置
AI_PROVIDER_TYPE: "dify"  # AI提供商类型：dify
AI_API_URL: "https://api.dify.ai"  # Dify API地址
AI_API_KEY: "xxx"  # Dify API密钥
AI_MODEL: "gpt-3.5-turbo"  # 使用的模型
AI_TIMEOUT: 30  # API超时时间（秒）
AI_MAX_RETRIES: 3  # 最大重试次数

# 服务配置
HTTP_PORT: 9000  # HTTP服务端口
HTTPS_PORT: 9001  # HTTPS服务端口（如果使用）
USE_HTTPS: false  # 是否使用HTTPS
CERT_FILE: "cert.pem"  # SSL证书文件
KEY_FILE: "key.pem"  # SSL密钥文件
ENABLE_LOG: true  # 是否启用日志

# 代理配置（可选）
HTTP_PROXY: ""  # HTTP代理地址
